/*
 * File Name: ultrasonic.c
 *
 * Created on: Oct 13, 2021
 *
 * Author: Nadeen Magdy
 */

#include <avr/io.h>
#include <util/delay.h>
#include "common_macros.h"
#include "icu.h"
#include "gpio.h"
#include "std_types.h"
#include "ultrasonic.h"

uint8 g_edgeCount = 0;
uint16 g_timerValue = 0;

/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the
   GPIO driver.
 */

void Ultrasonic_init (void)
{

	Icu_ConfigType ICU_Config = {F_CPU_8 , RISING};
	Icu_init(&ICU_Config);

	Icu_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */

void Ultrasonic_Trigger(void)
{
	SET_BIT(PORTB,5);
	_delay_us(10);
	CLEAR_BIT(PORTB,5);
}

/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Return: The measured distance in Centimeter.
 */

uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();

	uint16 distance = (float)g_timerValue / 58;
	return distance;
}

/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
   the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing (void)
{
	g_edgeCount ++;

	if(g_edgeCount == 1)
	{
		Icu_clearTimerValue();

		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		g_timerValue = Icu_getInputCaptureValue();

		Icu_setEdgeDetectionType(RISING);

		g_edgeCount = 0;
	}

}
